import assert from "node:assert/strict";
import test from "node:test";
import { assessProcurementRequests, type FundingPlan } from "../lib/procurement-request-funding";

const base = { asOf: "2026-09-15", salary: { dueOn: "2026-09-16", amountMinor: 50_000_000 }, rent: { dueOn: "2026-09-20", amountMinor: 23_500_000 }, safeMinor: 60_000_000, cardsMinor: 30_000_000, bankAccountsMinor: 100_000_000, vtbCardMinor: 20_000_000, vtbAccountMinor: 40_000_000, tbankCardMinor: 10_000_000, tbankAccountMinor: 60_000_000, tbankTransferStatus: "verified" as const, tbankCurrentRateBps: 100, tbankCurrentTierRemainingMinor: 80_000_000, usdtBalance: 5_000, accountableBalanceMinor: 20_000_000, usdtRate: 89 };
const plan = (data: Partial<FundingPlan> & Pick<FundingPlan, "id" | "paymentMethod">): FundingPlan => ({ status: "SUBMITTED", plannedDate: "2026-09-18", remainingMinor: 10_000_000, foreignAmount: null, ...data });

test("shows the USDT shortfall after already approved payments", () => { const plans = [plan({ id: "approved", status: "APPROVED", paymentMethod: "USDT", foreignAmount: 1_000 }), plan({ id: "request", paymentMethod: "USDT", remainingMinor: 44_500_000, foreignAmount: 5_000 })]; const [result] = assessProcurementRequests({ ...base, plans }); assert.equal(result.state, "prepare"); assert.equal(result.foreignAmount, 1_000); assert.equal(result.amountMinor, 8_900_000); });
test("cash request includes salary and gives a VTB then T-Bank preparation route", () => { const [result] = assessProcurementRequests({ ...base, plans: [plan({ id: "cash", paymentMethod: "CASH", remainingMinor: 70_000_000 })], safeMinor: 10_000_000 }); assert.equal(result.state, "prepare"); assert.equal(result.amountMinor, 110_000_000); assert.deepEqual(result.steps.map((step) => step.source), ["vtb", "tbank_card", "tbank_account"]); });
test("QR request tells how much to transfer to Astemir", () => { const [result] = assessProcurementRequests({ ...base, plans: [plan({ id: "qr", paymentMethod: "ACCOUNTABLE_QR", remainingMinor: 25_000_000 })] }); assert.equal(result.state, "prepare"); assert.equal(result.amountMinor, 5_000_000); });
test("never claims coverage when a required balance is unavailable", () => { const [result] = assessProcurementRequests({ ...base, plans: [plan({ id: "cash", paymentMethod: "CASH" })], safeMinor: null }); assert.equal(result.state, "unavailable"); });
